version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  # Enables hot reloading in Docker
    restart: unless-stopped
    stdin_open: true # docker run -i
    tty: true        # docker run -t